
package ep2.base.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Fabrica", targetNamespace = "http://server.base.ep2/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Fabrica {


    /**
     * 
     * @param produtos
     * @param quantidades
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "produz", targetNamespace = "http://server.base.ep2/", className = "ep2.base.client.Produz")
    @ResponseWrapper(localName = "produzResponse", targetNamespace = "http://server.base.ep2/", className = "ep2.base.client.ProduzResponse")
    public long produz(
        @WebParam(name = "produtos", targetNamespace = "")
        List<Integer> produtos,
        @WebParam(name = "quantidades", targetNamespace = "")
        List<Integer> quantidades);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isProducaoPronta", targetNamespace = "http://server.base.ep2/", className = "ep2.base.client.IsProducaoPronta")
    @ResponseWrapper(localName = "isProducaoProntaResponse", targetNamespace = "http://server.base.ep2/", className = "ep2.base.client.IsProducaoProntaResponse")
    public boolean isProducaoPronta(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

}
